---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
            name: "Remove trailing whitespaces"
          - id: end-of-file-fixer
            name: "Fix newline at end of files"
          - id: debug-statements
            description: Check for debugger imports and py37+ breakpoint() calls
          - id: mixed-line-ending
            name: "Use linux line endings"
            args: ["--fix=lf"]
            description: Force replacement of line ending by the UNIX 'lf' character
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint
            args: ["-c=.yamllint"]
    - repo: https://github.com/psf/black
      rev: 23.11.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]
            types: [python]
            language: python
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-docstrings
