name: Python Test and Coverage

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # without submodules

            - name: Disable the keychain credential helper
              run: git config --global credential.helper ""

            - name: Enable the local store credential helper
              run: git config --global --add credential.helper store

            - name: Add credential
              run: echo "https://x-access-token:${{ secrets.SUBMODULE_GITHUB_TOKEN }}@github.com" >> ~/.git-credentials

            - name: Tell git to use https instead of ssh whenever it encounters it
              run: 'git config --global url."https://github.com/".insteadof git@github.com:'

            - name: Git submodule initialization
              run: |
                  git submodule update --init --recursive

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: "3.9"
                  # Optional - x64 or x86 architecture, defaults to x64
                  architecture: "x64"

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  if [ -f requirements.extras.txt ]; then pip install -r requirements.extras.txt; fi
                  pip install pytest pytest-cov

            - name: Run pytest with coverage
              run: |
                  python3 -m coverage run -m pytest tests --junitxml=report.xml --ignore=tests/integration_tests
                  coverage report -i --include=selfclean/* --omit="selfclean/ssl_library/*"
                  coverage xml -i --include=selfclean/* --omit="selfclean/ssl_library/*"
                  codecov

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4
              env:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: Digital-Dermatology/SelfClean
